spring:
  profiles:
    include:
      - ai
      - member
      - discord
      - database

logging:
  level:
    root: info
    com.zaxxer.hikari.pool.HikariPool: info
    exposed: debug

dev:
  kuro9:
    smartapp:
      token: ${SMARTAPP_TOKEN}
    jwt:
      key: test123
    webhook:
      url: ${DISCORD_ERROR_WEBHOOK}