spring:
  datasource:
    url: ${PGSQL_URL}
    username: ${PGSQL_USER}
    password: ${PGSQL_PW}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 4
      maximum-pool-size: 24
  exposed:
    generate-ddl: false
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${OAUTH2_DISCORD_CLIENT_ID}
            client-secret: ${OAUTH2_DISCORD_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            client-name: discord
            redirect-uri: ${BASE_URL}/login/oauth2/code/discord
            scope:
              - identify
            authorization-grant-type: authorization_code
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/oauth2/@me
            user-name-attribute: id

logging:
  level:
    root: info
    com.zaxxer.hikari.pool.HikariPool: info
    exposed: debug

dev:
  kuro9:
    discord:
      token: ${DISCORD_TOKEN}
    smartapp:
      token: ${SMARTAPP_TOKEN}
    jwt:
      key: test123
      redirect-url: ${BASE_URL}/login/success