spring:
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${OAUTH2_DISCORD_CLIENT_ID}
            client-secret: ${OAUTH2_DISCORD_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            client-name: discord
            redirect-uri: ${BASE_URL}/login/oauth2/code/discord
            scope:
              - identify
            authorization-grant-type: authorization_code
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/oauth2/@me
            user-name-attribute: user